language: csharp
sudo: required 
dist: trusty
env:  
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g  
os:  
  - linux
# - osx
#osx_image: xcode7.1  
branches:  
  only:
    - master
before_install:  
  - chmod +x build.sh
  # - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo apt-get update
install:  
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo apt-get install dotnet-dev-1.0.0-preview2-003121
script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  # - grep "Build Results" build.log
#  - ./test.sh
  