/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.Samples
{

  /// <summary>
  /// Structs can also be exceptions, if they are nasty.
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class InvalidOperation : TException, TBase
  {
    private int _WhatOp;
    private string _Why;

    public int WhatOp
    {
      get
      {
        return _WhatOp;
      }
      set
      {
        __isset.WhatOp = true;
        this._WhatOp = value;
      }
    }

    public string Why
    {
      get
      {
        return _Why;
      }
      set
      {
        __isset.Why = true;
        this._Why = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool WhatOp;
      public bool Why;
    }

    public InvalidOperation() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                WhatOp = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Why = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("InvalidOperation");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.WhatOp) {
          field.Name = "WhatOp";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(WhatOp);
          oprot.WriteFieldEnd();
        }
        if (Why != null && __isset.Why) {
          field.Name = "Why";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Why);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("InvalidOperation(");
      bool __first = true;
      if (__isset.WhatOp) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("WhatOp: ");
        __sb.Append(WhatOp);
      }
      if (Why != null && __isset.Why) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Why: ");
        __sb.Append(Why);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
